# Generated by Django 6.0.1 on 2026-01-28 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='연락처')),
            ],
            options={
                'verbose_name': '인원',
                'verbose_name_plural': '인원 목록',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('HQ', '본부'), ('BR', '지사'), ('REL', '종교')], max_length=10, verbose_name='대분류')),
                ('name', models.CharField(max_length=100, verbose_name='업무명 (선택 항목)')),
            ],
            options={
                'verbose_name': '업무 항목',
                'verbose_name_plural': '업무 항목 관리',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, max_length=200, verbose_name='상세 내용 (공연명 등)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='배정일시')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personnel', verbose_name='담당자')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.task', verbose_name='배정 업무')),
            ],
            options={
                'verbose_name': '업무 배분',
                'verbose_name_plural': '업무 배분 현황',
            },
        ),
    ]
