# Generated by Django 6.0.1 on 2026-01-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={'verbose_name': '인원', 'verbose_name_plural': '인원 명단'},
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='phone',
        ),
        migrations.AddField(
            model_name='personnel',
            name='position',
            field=models.CharField(default='', max_length=50, verbose_name='직급'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='팀명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('members', models.ManyToManyField(related_name='teams', to='core.personnel', verbose_name='팀원')),
            ],
            options={
                'verbose_name': '팀',
                'verbose_name_plural': '팀 목록',
            },
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
